version: "3.8"

services:
  vladicore-api:
    image: ghcr.io/shinozakiaichi/vladicore-api:${IMAGE_TAG:-latest}
    container_name: vladicore-api
    restart: unless-stopped
    ports:
      - "8888:8080"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      Jwt__Key: "${JWT_KEY}"
      # Пример: НИ КАКОГО localhost
      
      # Host=postgres, потому что контейнер postgres в той же сети Vladislave
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=shinozaki_db;Username=aichishinozaki;Password=aichishinozaki651;Include Error Detail=true;Search Path=public,core,catalog,sales,inventory"
    networks:
      - vladislave
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/8080' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  vladislave:
    external: true
    name: Vladislave
