version: '3.9'

services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: vladicore-api
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS:-http://+:8080}
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: ${DOTNET_SYSTEM_GLOBALIZATION_INVARIANT:-0}
      ConnectionStrings__Default: "${ConnectionStrings__Default:-Server=vladicore-mysql;Port=3306;Database=vladicore;User Id=vladicore;Password=devpass;TreatTinyAsBoolean=true;CharSet=utf8mb4;}"
      Jwt__Issuer: ${Jwt__Issuer:-VladiCore}
      Jwt__Audience: ${Jwt__Audience:-VladiCore}
      Jwt__SigningKey: ${Jwt__SigningKey:-replace-with-secure-key}
      Jwt__AccessTokenTtlSeconds: ${Jwt__AccessTokenTtlSeconds:-900}
      Jwt__RefreshTokenTtlSeconds: ${Jwt__RefreshTokenTtlSeconds:-1209600}
      Serilog__MinimumLevel__Default: ${Serilog__MinimumLevel__Default:-Information}
      Serilog__MinimumLevel__Override__Microsoft: ${Serilog__MinimumLevel__Override__Microsoft:-Warning}
      Serilog__MinimumLevel__Override__System: ${Serilog__MinimumLevel__Override__System:-Warning}
      Database__AutoProvision__Enabled: ${Database__AutoProvision__Enabled:-true}
      Database__AutoProvision__ApplySeeds: ${Database__AutoProvision__ApplySeeds:-false}
      Database__AutoProvision__TimeoutSeconds: ${Database__AutoProvision__TimeoutSeconds:-120}
      Database__AutoProvision__MigrationsPath: ${Database__AutoProvision__MigrationsPath:-db/migrations/mysql}
      Database__AutoProvision__SeedsPath: ${Database__AutoProvision__SeedsPath:-db/seed}
      Database__AutoProvision__CreateDbIfMissing: ${Database__AutoProvision__CreateDbIfMissing:-true}
      Database__AutoProvision__DatabaseName: ${Database__AutoProvision__DatabaseName:-vladicore}
    ports:
      - "${API_HTTP_PORT:-8080}:8080"
    networks:
      - backend

networks:
  backend:
    name: ${DOCKER_NETWORK_NAME:-vladicore-backend}
    external: ${DOCKER_NETWORK_EXTERNAL:-true}
