version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: vladicore-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: vladicore
      MYSQL_USER: vladicore
      MYSQL_PASSWORD: devpass
      TZ: UTC
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
