version: '3.9'

services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: vladicore-api
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS:-http://+:8080}
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: ${DOTNET_SYSTEM_GLOBALIZATION_INVARIANT:-0}
      ConnectionStrings__Default: "${ConnectionStrings__Default:-Server=vladicore-mysql;Port=3306;Database=vladicore;User Id=vladicore;Password=devpass;TreatTinyAsBoolean=true;CharSet=utf8mb4;}"
      Jwt__Issuer: ${Jwt__Issuer:-VladiCore}
      Jwt__Audience: ${Jwt__Audience:-VladiCore}
      Jwt__SigningKey: ${Jwt__SigningKey:-replace-with-secure-key}
      Serilog__MinimumLevel__Default: ${Serilog__MinimumLevel__Default:-Information}
      Serilog__MinimumLevel__Override__Microsoft: ${Serilog__MinimumLevel__Override__Microsoft:-Warning}
      Serilog__MinimumLevel__Override__System: ${Serilog__MinimumLevel__Override__System:-Warning}
    ports:
      - "${API_HTTP_PORT:-8080}:8080"
    networks:
      - backend

networks:
  backend:
    name: ${DOCKER_NETWORK_NAME:-vladicore-backend}
    external: ${DOCKER_NETWORK_EXTERNAL:-true}
