SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS ProductPriceHistory;
DROP TABLE IF EXISTS ProductViews;
DROP TABLE IF EXISTS OrderItems;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Cpus;
DROP TABLE IF EXISTS Motherboards;
DROP TABLE IF EXISTS Rams;
DROP TABLE IF EXISTS Gpus;
DROP TABLE IF EXISTS Psus;
DROP TABLE IF EXISTS Cases;
DROP TABLE IF EXISTS Coolers;
DROP TABLE IF EXISTS Storages;

CREATE TABLE Categories (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(128) NOT NULL,
  ParentId INT NULL,
  CreatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  INDEX IX_Categories_ParentId (ParentId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Products (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Sku VARCHAR(64) NOT NULL,
  Name VARCHAR(256) NOT NULL,
  CategoryId INT NOT NULL,
  Price DECIMAL(12,2) NOT NULL,
  OldPrice DECIMAL(12,2) NULL,
  Attributes JSON NULL,
  CreatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  INDEX IX_Products_CategoryId (CategoryId),
  INDEX IX_Products_Price (Price),
  CONSTRAINT FK_Products_Categories FOREIGN KEY (CategoryId) REFERENCES Categories (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ProductPriceHistory (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  ProductId INT NOT NULL,
  Price DECIMAL(12,2) NOT NULL,
  ChangedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  INDEX IX_PriceHistory_ProductId_ChangedAt (ProductId, ChangedAt DESC),
  CONSTRAINT FK_PriceHistory_Product FOREIGN KEY (ProductId) REFERENCES Products (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Orders (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  UserId INT NULL,
  CreatedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE OrderItems (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  OrderId INT NOT NULL,
  ProductId INT NOT NULL,
  Qty INT NOT NULL,
  UnitPrice DECIMAL(12,2) NOT NULL,
  INDEX IX_OrderItems_ProductId (ProductId),
  INDEX IX_OrderItems_Order_Product (OrderId, ProductId),
  CONSTRAINT FK_OrderItems_Orders FOREIGN KEY (OrderId) REFERENCES Orders (Id) ON DELETE CASCADE,
  CONSTRAINT FK_OrderItems_Products FOREIGN KEY (ProductId) REFERENCES Products (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ProductViews (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  ProductId INT NOT NULL,
  UserId INT NULL,
  SessionId VARCHAR(64) NOT NULL,
  ViewedAt DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  INDEX IX_ProductViews_ProductId_ViewedAt (ProductId, ViewedAt),
  CONSTRAINT FK_ProductViews_Product FOREIGN KEY (ProductId) REFERENCES Products (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Cpus (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(128) NOT NULL,
  Socket VARCHAR(32) NOT NULL,
  Tdp INT NOT NULL,
  PerfScore INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Motherboards (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(128) NOT NULL,
  Socket VARCHAR(32) NOT NULL,
  RamType VARCHAR(16) NOT NULL,
  RamMaxFreq INT NOT NULL,
  M2Slots INT NOT NULL,
  PcieSlots INT NOT NULL,
  FormFactor VARCHAR(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Rams (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(128) NOT NULL,
  Type VARCHAR(16) NOT NULL,
  Freq INT NOT NULL,
  CapacityPerStick INT NOT NULL,
  Sticks INT NOT NULL,
  PerfScore INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Gpus (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(128) NOT NULL,
  LengthMm INT NOT NULL,
  Slots INT NOT NULL,
  Tdp INT NOT NULL,
  PerfScore INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Psus (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(128) NOT NULL,
  Wattage INT NOT NULL,
  FormFactor VARCHAR(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Cases (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(128) NOT NULL,
  GpuMaxLengthMm INT NOT NULL,
  CoolerMaxHeightMm INT NOT NULL,
  PsuFormFactor VARCHAR(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Coolers (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(128) NOT NULL,
  HeightMm INT NOT NULL,
  SocketSupport JSON NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Storages (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(128) NOT NULL,
  Type ENUM('HDD','SATA_SSD','NVME') NOT NULL,
  CapacityGb INT NOT NULL,
  PerfScore INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TRIGGER IF EXISTS trg_products_price_history;
DELIMITER $$
CREATE TRIGGER trg_products_price_history
BEFORE UPDATE ON Products
FOR EACH ROW
BEGIN
  IF NEW.Price <> OLD.Price THEN
    INSERT INTO ProductPriceHistory(ProductId, Price, ChangedAt)
    VALUES (OLD.Id, NEW.Price, UTC_TIMESTAMP(6));
    SET NEW.OldPrice = OLD.Price;
  END IF;
END$$
DELIMITER ;

SET FOREIGN_KEY_CHECKS = 1;
