name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "stack.env"        # чтобы автокоммит bump не пересобирал образ бесконечно
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore with cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - run: dotnet restore
      - run: dotnet build --no-restore -c Release
      - run: dotnet test --no-build -c Release --logger "trx;LogFileName=test-results.trx"

  docker:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      packages: write        # GHCR push
      contents: write        # для автокоммита
    steps:
      - uses: actions/checkout@v4

      - name: Lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Set image name
        run: echo "IMAGE=ghcr.io/${OWNER_LC}/vladicore-api" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ github.ref }}-
            buildx-

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64         # если нужен arm64 — добавишь
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move build cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Bump IMAGE_TAG in stack.env to current SHA
        run: |
          SHA=${{ github.sha }}
          sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=$SHA/" stack.env || echo "IMAGE_TAG=$SHA" > stack.env
          git status --porcelain

      - name: Commit stack.env bump [skip ci]
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(ci): bump IMAGE_TAG -> ${{ github.sha }} [skip ci]"
          file_pattern: stack.env
